

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
SCREEN_TITLE = "Platformer"
CHARACTER_SCALING = .5
TILE_SCALING = 0.5
COIN_SCALING = 0.5
STARTING_PLAYER_MOVEMENT_SPEED = 5
zombie_image = ":resources:images/animated_characters/zombie/zombie_idle.png"
SPRITE_SCALING_LASER = .8
BULLET_SPEED = 25
SPRITE_NATIVE_SIZE = 128
SPRITE_SIZE = int(SPRITE_NATIVE_SIZE * CHARACTER_SCALING)
RIGHT_FACING = 0
LEFT_FACING = 1
UPDATES_PER_FRAME = 5